import 'package:flutter/material.dart';

import '../../core/theme/app_colors.dart';
import '../../core/widgets/app_message.dart';
import '../../core/widgets/app_text_field.dart';
import '../../l10n/app_localizations.dart';
import 'services/password_reset_service.dart';

/// Offline alternative to the OTP forgot-password flow — no email/SMS/API
/// involved at all. Reached from [ForgotPasswordScreen] via a text link;
/// collects username + the recovery code shown once at shop bootstrap (or
/// since regenerated by the owner in Settings) + a new password, all in one
/// screen since there's no separate "request" step like OTP has.
class RecoveryCodeScreen extends StatefulWidget {
  const RecoveryCodeScreen({super.key});

  @override
  State<RecoveryCodeScreen> createState() => _RecoveryCodeScreenState();
}

class _RecoveryCodeScreenState extends State<RecoveryCodeScreen> {
  final _formKey = GlobalKey<FormState>();
  final _usernameController = TextEditingController();
  final _codeController = TextEditingController();
  final _passwordController = TextEditingController();
  final _confirmController = TextEditingController();
  final _service = PasswordResetService();

  bool _obscurePassword = true;
  bool _obscureConfirm = true;
  bool _loading = false;
  String? _error;

  @override
  void dispose() {
    _usernameController.dispose();
    _codeController.dispose();
    _passwordController.dispose();
    _confirmController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;

    setState(() {
      _loading = true;
      _error = null;
    });

    final ok = await _service.recoverWithCode(
      _usernameController.text.trim(),
      _codeController.text.trim(),
      _passwordController.text,
    );

    if (!mounted) return;
    setState(() => _loading = false);

    if (ok) {
      final message = AppLocalizations.of(context)!.resetPasswordSuccessMessage;
      Navigator.of(context).popUntil((route) => route.isFirst);
      showAppMessage(context, message);
    } else {
      setState(
        () => _error = AppLocalizations.of(context)!.recoveryCodeResetErrorMessage,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 400),
              child: Form(
                key: _formKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Container(
                      width: 72,
                      height: 72,
                      decoration: const BoxDecoration(
                        color: AppColors.primary,
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(
                        Icons.key_outlined,
                        color: AppColors.accent,
                        size: 34,
                      ),
                    ),
                    const SizedBox(height: 20),
                    Text(
                      l10n.recoveryCodeResetTitle,
                      style: Theme.of(context).textTheme.headlineMedium,
                    ),
                    const SizedBox(height: 4),
                    Text(
                      l10n.recoveryCodeResetInstructions,
                      textAlign: TextAlign.center,
                      style: const TextStyle(color: AppColors.muted, fontSize: 12),
                    ),
                    const SizedBox(height: 32),
                    Card(
                      child: Padding(
                        padding: const EdgeInsets.all(24),
                        child: Column(
                          children: [
                            AppTextField(
                              label: l10n.usernameOrEmailLabel,
                              controller: _usernameController,
                              validator: (v) => (v == null || v.trim().isEmpty)
                                  ? l10n.forgotPasswordValidator
                                  : null,
                            ),
                            const SizedBox(height: 14),
                            AppTextField(
                              label: l10n.recoveryCodeLabel,
                              controller: _codeController,
                              hintText: l10n.recoveryCodeHint,
                              validator: (v) => (v == null || v.trim().isEmpty)
                                  ? l10n.recoveryCodeRequiredError
                                  : null,
                            ),
                            const SizedBox(height: 14),
                            AppTextField(
                              label: l10n.resetPasswordNewPasswordLabel,
                              controller: _passwordController,
                              obscureText: _obscurePassword,
                              validator: (v) {
                                if (v == null || v.isEmpty) {
                                  return l10n.passwordRequiredValidator;
                                }
                                if (v.length < 8) {
                                  return l10n.resetPasswordLengthValidator;
                                }
                                return null;
                              },
                              suffixIcon: IconButton(
                                icon: Icon(
                                  _obscurePassword
                                      ? Icons.visibility_off
                                      : Icons.visibility,
                                ),
                                onPressed: () => setState(
                                  () => _obscurePassword = !_obscurePassword,
                                ),
                              ),
                            ),
                            const SizedBox(height: 14),
                            AppTextField(
                              label: l10n.confirmPasswordLabel,
                              controller: _confirmController,
                              obscureText: _obscureConfirm,
                              validator: (v) {
                                if (v == null || v.isEmpty) {
                                  return l10n.resetPasswordConfirmEmptyValidator;
                                }
                                if (v != _passwordController.text) {
                                  return l10n.passwordMismatchValidator;
                                }
                                return null;
                              },
                              suffixIcon: IconButton(
                                icon: Icon(
                                  _obscureConfirm
                                      ? Icons.visibility_off
                                      : Icons.visibility,
                                ),
                                onPressed: () => setState(
                                  () => _obscureConfirm = !_obscureConfirm,
                                ),
                              ),
                            ),
                            if (_error != null) ...[
                              const SizedBox(height: 12),
                              Align(
                                alignment: Alignment.centerLeft,
                                child: Text(
                                  _error!,
                                  style: const TextStyle(
                                    color: AppColors.terracottaDark,
                                    fontSize: 12,
                                  ),
                                ),
                              ),
                            ],
                            const SizedBox(height: 20),
                            SizedBox(
                              width: double.infinity,
                              child: ElevatedButton(
                                onPressed: _loading ? null : _submit,
                                child: _loading
                                    ? const SizedBox(
                                        width: 20,
                                        height: 20,
                                        child: CircularProgressIndicator(
                                          strokeWidth: 2,
                                          color: AppColors.accent,
                                        ),
                                      )
                                    : Text(l10n.recoveryCodeResetButton),
                              ),
                            ),
                            const SizedBox(height: 4),
                            TextButton(
                              onPressed: () => Navigator.of(context).pop(),
                              child: Text(l10n.forgotPasswordBackLink),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
